import Head from "next/head";
import Image from "next/image";
import Button from "../components/Button";
import Icons from "../components/Icons";
import Nav from "../components/Nav";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Nav />

      <main className="max-w-5xl mx-auto px-8 mt-24">
        <div className="flex flex-col gap-16">
          <h1 className="font-black text-7xl tracking-tight leading-[1.15]">
            The workflow for icons from Figma → React, in seconds.
          </h1>

          <Button size="large">Get started</Button>
        </div>

        <Icons />
      </main>
    </div>
  );
}
